export const API_CLIENT_ERROR_CODE = {
  CANCELED: "CANCELED",
  HTTP_ERROR: "HTTP_ERROR",
  INVALID_API_RESPONSE: "INVALID_API_RESPONSE",
  NETWORK_ERROR: "NETWORK_ERROR",
  TIMEOUT: "TIMEOUT",
} as const;

export type ApiClientErrorCode =
  (typeof API_CLIENT_ERROR_CODE)[keyof typeof API_CLIENT_ERROR_CODE];
